// Autogenerated from Pigeon (v1.0.8), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Book;

@interface Book : NSObject
@property(nonatomic, copy, nullable) NSString * title;
@property(nonatomic, copy, nullable) NSString * author;
@end

/// The codec used by BookApi.
NSObject<FlutterMessageCodec> *BookApiGetCodec(void);

@interface BookApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)searchKeyword:(NSString *)keyword completion:(void(^)(NSArray<Book *> *, NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
